//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arabology_ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int AccountId { get; set; }
        public string AccountNameA { get; set; }
        public string AccountNameE { get; set; }
        public string AccountCode { get; set; }
        public Nullable<short> NatureAccount { get; set; }
        public Nullable<short> FinalAccount { get; set; }
        public Nullable<short> FinalState { get; set; }
        public Nullable<int> ParentId { get; set; }
    }
}
