//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arabology_ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Sales = new HashSet<Sale>();
            this.Sales1 = new HashSet<Sale>();
        }
    
        public int CustomerId { get; set; }
        public string CustomerNameA { get; set; }
        public string CustomerNameE { get; set; }
        public string Address { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<decimal> CreditsLimit { get; set; }
        public Nullable<bool> CreditState { get; set; }
        public string LiceneseId { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> TremId { get; set; }
        public Nullable<bool> InActive { get; set; }
        public Nullable<bool> BadPayer { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> PriceListId { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Category Category { get; set; }
        public virtual City City { get; set; }
        public virtual Class Class { get; set; }
        public virtual PriceList PriceList { get; set; }
        public virtual Region Region { get; set; }
        public virtual Term Term { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales1 { get; set; }
    }
}
