//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arabology_ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.SalesLines = new HashSet<SalesLine>();
        }
    
        public int ItemId { get; set; }
        public string ItemNameA { get; set; }
        public string ItemNameE { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> ItemTypeId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> ItemSubTypeId { get; set; }
        public Nullable<bool> InActive { get; set; }
        public string MainUOM { get; set; }
        public string LargeUOM { get; set; }
        public string SmallUOM { get; set; }
        public string SalesUOM { get; set; }
        public string PurchaseUOM { get; set; }
        public string InventoryUOM { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        public virtual Country Country { get; set; }
        public virtual CalcUnitOfMeasure CalcUnitOfMeasure { get; set; }
        public virtual ItemSubType ItemSubType { get; set; }
        public virtual ItemType ItemType { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure1 { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure2 { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure3 { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure4 { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesLine> SalesLines { get; set; }
    }
}
