//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arabology_ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesLine
    {
        public int SalesLineId { get; set; }
        public int SalesId { get; set; }
        public int ItemId { get; set; }
        public int Qty { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Promotion { get; set; }
        public Nullable<decimal> LineTotal { get; set; }
        public decimal CostLine { get; set; }
        public string UOM { get; set; }
        public int StoreIdFrom { get; set; }
        public Nullable<int> StoreIdTo { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Sale Sale { get; set; }
        public virtual Store Store { get; set; }
        public virtual Store Store1 { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
    }
}
