//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arabology_ERP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.SalesLines = new HashSet<SalesLine>();
        }
    
        public int SalesId { get; set; }
        public string DocNo { get; set; }
        public Nullable<int> SectorId { get; set; }
        public Nullable<int> SalesManId { get; set; }
        public Nullable<int> DliverymanId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> PriceListId { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Total { get; set; }
        public decimal Discount { get; set; }
        public decimal Taxes { get; set; }
        public Nullable<decimal> NetTotal { get; set; }
        public Nullable<bool> State { get; set; }
        public string Note { get; set; }
        public string CusPO { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public int CreatedUserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedUserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int ActivedUser { get; set; }
        public int StoreId { get; set; }
        public Nullable<decimal> Promotion { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Customer Customer1 { get; set; }
        public virtual DeliveryMan DeliveryMan { get; set; }
        public virtual PriceList PriceList { get; set; }
        public virtual Salesman Salesman { get; set; }
        public virtual Sector Sector { get; set; }
        public virtual Sector Sector1 { get; set; }
        public virtual Store Store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesLine> SalesLines { get; set; }
    }
}
